In [6]:
import pandas as pd

In [12]:
import numpy as np

In [5]:
tips = pd.read_csv(r"C:\Users\Lenovo\Desktop\seaborn-data\tips.csv")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

#### Mean of Totalbill

In [10]:
bill_mean = tips['total_bill'].mean()
bill_mean

19.78594262295082

#### Standard deviation of Totalbill

In [8]:
totalbill_std = tips['total_bill'].std()
totalbill_std

8.902411954856856

#### coefficient of variation of Totalbill

In [11]:
totalbill_std/bill_mean

0.44993620594706724

#### Quartiles of Totalbill

In [24]:
q1_bill = np.quantile(tips['total_bill'],q=0.25)
q1_bill

13.3475

* first Quartile = 13.3475

In [25]:
q2_bill = np.quantile(tips['total_bill'],q=0.50)
q2_bill

17.795

* second quartile = 17.795

In [26]:
q3_bill = np.quantile(tips['total_bill'],q=0.75)
q3_bill

24.127499999999998

* Third quartile = 24.12

#### Inter quartile range of totalbill

In [27]:
q3_bill - q1_bill

10.779999999999998

#### Quartile coefficient of dispersion of totalbill

In [28]:
(q3_bill-q1_bill)/(q3_bill+q1_bill)

0.2876584389593062

In [29]:
ds_salaries = pd.read_csv(r"C:\Users\Lenovo\Documents\ds_salaries.csv.xls")
ds_salaries

Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Data Engineer   85000             GBP         109024   
3          Product Data Analyst   20000             USD          20000   
4     Machine Learning Engineer  150000             USD         150000   
..                          ...     ...             ...            ...   
602               Data Engineer  154000             USD         154000   
603               Data Engineer  126000             USD         126000   
604                Data Analyst  129000             USD         129000   
605                Data Analyst  150000             USD         150000   
606                AI Scientist  200000             USD         200000   

    employee_residence  remote_ratio company_location company_size  
0                   DE             0               DE            L  
1                   JP             0               JP            S  
2                   GB            50               GB            M  
3                   HN             0               HN            S  
4                   US            50               US            L  
..                 ...           ...              ...          ...  
602                 US           100               US            M  
603                 US           100               US            M  
604                 US             0               US            M  
605                 US           100               US            M  
606                 IN           100               US            L  

[607 rows x 12 columns]

#### Mean of salary in usd

In [31]:
salary_mean = ds_salaries['salary_in_usd'].mean()
salary_mean

112297.86985172982

#### Standard deviation of salary in usd

In [32]:
salary_std = ds_salaries['salary_in_usd'].std()
salary_std

70957.2594113957

#### Coefficient of variation of salary in usd

In [33]:
salary_std/salary_mean

0.6318664771209166

#### Quartiles of salary in usd

In [34]:
q1_salary = np.quantile(ds_salaries['salary_in_usd'],q=0.25)
q1_salary

62726.0

* first quartile of salary in usd = 62726

In [35]:
q2_salary = np.quantile(ds_salaries['salary_in_usd'],q=0.50)
q2_salary

101570.0

* second quartile of salary in usd = 101570

In [36]:
q3_salary = np.quantile(ds_salaries['salary_in_usd'],q=0.75)
q3_salary

150000.0

* third quartile of salary in usd

#### Inter quartile range of salary in usd

In [37]:
q3_salary - q1_salary

87274.0

#### Quartile coefficient of dispersion of salary in usd

In [39]:
(q3_salary - q1_salary) / (q3_salary + q1_salary)

0.41026484773840527

In [40]:
taxis = pd.read_csv(r"C:\Users\Lenovo\Desktop\seaborn-data\taxis.csv")
taxis

pickup              dropoff  passengers  distance  fare  \
0     2019-03-23 20:21:09  2019-03-23 20:27:24           1      1.60   7.0   
1     2019-03-04 16:11:55  2019-03-04 16:19:00           1      0.79   5.0   
2     2019-03-27 17:53:01  2019-03-27 18:00:25           1      1.37   7.5   
3     2019-03-10 01:23:59  2019-03-10 01:49:51           1      7.70  27.0   
4     2019-03-30 13:27:42  2019-03-30 13:37:14           3      2.16   9.0   
...                   ...                  ...         ...       ...   ...   
6428  2019-03-31 09:51:53  2019-03-31 09:55:27           1      0.75   4.5   
6429  2019-03-31 17:38:00  2019-03-31 18:34:23           1     18.74  58.0   
6430  2019-03-23 22:55:18  2019-03-23 23:14:25           1      4.14  16.0   
6431  2019-03-04 10:09:25  2019-03-04 10:14:29           1      1.12   6.0   
6432  2019-03-13 19:31:22  2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
6428  1.06    0.0   6.36   green  credit card      East Harlem North   
6429  0.00    0.0  58.80   green  credit card                Jamaica   
6430  0.00    0.0  17.30   green         cash    Crown Heights North   
6431  0.00    0.0   6.80   green  credit card          East New York   
6432  3.36    0.0  20.16   green  credit card            Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 14 columns]

#### Mean of fare

In [42]:
fare_mean = taxis['fare'].mean()
fare_mean

13.091072594434944

#### Standard deviation of fare

In [44]:
fare_std = taxis['fare'].std()
fare_std

11.55180426641491

#### Coefficient of variation of fare

In [45]:
fare_std/fare_mean

0.882418471296662

#### Quartiles of fare

In [51]:
q1_fare = np.quantile(taxis['fare'],q=0.25)
q1_fare

6.5

* first quartile of fare = 6.5

In [52]:
q2_fare = np.quantile(taxis['fare'],q=0.50)
q2_fare

9.5

* second quartile of fare = 9.5

In [53]:
q3_fare = np.quantile(taxis['fare'],q=0.75)
q3_fare

15.0

* third quartile of fare = 15

#### Inter quartile range

In [54]:
q3_fare  - q1_fare

8.5

#### Quartile coefficient of dispersion

In [55]:
(q3_fare  - q1_fare) / (q3_fare  + q1_fare)

0.3953488372093023